# Generated by Django 5.2.6 on 2025-09-23 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='Ingrese un teléfono válido de 9 dígitos, sin espacios ni símbolos.')]),
        ),
    ]
