# Generated by Django 5.2.6 on 2025-10-24 18:43

import django.core.validators
import lista.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(help_text='Máximo 150 caracteres', max_length=150, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido'), lista.models.validar_correo_largo]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(help_text='Formato: +569XXXXXXXX (número chileno)', max_length=12, validators=[django.core.validators.RegexValidator('^\\+569\\d{8}$', message='Ingrese un teléfono válido en formato +569XXXXXXXX (ej: +56912345678)'), lista.models.validar_telefono_chileno]),
        ),
    ]
