# Generated by Django 5.2.6 on 2025-10-24 19:11

import django.core.validators
import lista.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_alter_contacto_correo_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(error_messages={'invalid': 'Ingrese solo el símbolo + al inicio seguido de números'}, help_text='Formato: +569XXXXXXXX (solo números después del +)', max_length=12, validators=[django.core.validators.RegexValidator('^\\+[0-9]+$', message='Solo se permite el símbolo + al inicio, seguido de números'), lista.models.validar_telefono_chileno]),
        ),
    ]
